server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: orders
  datasource:
    url: ${MYSQL_URI:jdbc:mysql://localhost:3306/orders_db?createDatabaseIfNotExist=true}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate: 
      ddl-auto: create
